# Generated by Django 6.1 on 2026-08-25 04:56

import django.db.models.deletion
import django.utils.timezone
import secrets
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricDeviceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(default='ZKTECO-GATE-01', max_length=50)),
                ('biometric_user_id', models.CharField(max_length=50)),
                ('punch_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('punch_type', models.CharField(choices=[('IN', 'Punch In'), ('OUT', 'Punch Out')], default='IN', max_length=20)),
                ('is_synced', models.BooleanField(default=True)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('target_url', models.URLField()),
                ('secret_token', models.CharField(default=secrets.token_hex, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('events_subscribed', models.TextField(default='employee.created,leave.approved,attendance.punch,payroll.disbursed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Biometric Attendance Sync Service, Mobile App Gateway', max_length=100)),
                ('key', models.CharField(default=secrets.token_hex, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rate_limit_per_minute', models.IntegerField(default=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
