# Generated by Django 6.1 on 2026-08-25 04:56

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=30)),
                ('current_company', models.CharField(blank=True, max_length=150)),
                ('current_designation', models.CharField(blank=True, max_length=150)),
                ('total_experience_years', models.DecimalField(decimal_places=1, default=Decimal('4.0'), max_digits=4)),
                ('current_ctc', models.DecimalField(decimal_places=2, default=Decimal('900000.00'), max_digits=12)),
                ('expected_ctc', models.DecimalField(decimal_places=2, default=Decimal('1200000.00'), max_digits=12)),
                ('notice_period_days', models.PositiveIntegerField(default=30)),
                ('current_location', models.CharField(default='Bengaluru', max_length=100)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('linkedin_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('skills_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('APPLIED', 'Application Received'), ('SCREENING', 'Resume Screened / Shortlisted'), ('TECH_INTERVIEW', 'Technical Evaluation'), ('MANAGERIAL', 'Managerial & Cultural Fit'), ('HR_ROUND', 'HR & Compensation Discussion'), ('OFFER_EXTENDED', 'Offer Letter Extended'), ('HIRED', 'Joined / Hired'), ('REJECTED', 'Not Selected / Rejected'), ('WITHDRAWN', 'Candidate Withdrew')], default='APPLIED', max_length=30)),
                ('source', models.CharField(choices=[('CAREERS_PORTAL', 'Careers Website'), ('LINKEDIN', 'LinkedIn'), ('EMPLOYEE_REFERRAL', 'Employee Referral'), ('AGENCY', 'Recruitment Agency'), ('DIRECT', 'Direct Inbound')], default='LINKEDIN', max_length=50)),
                ('match_score_percentage', models.IntegerField(default=85, help_text='AI/Rule match score out of 100')),
                ('overall_rating', models.DecimalField(decimal_places=1, default=Decimal('4.5'), max_digits=3)),
                ('recruiter_notes', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment.candidate')),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_referrals', to='employees.employee')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_name', models.CharField(default='Technical Architecture Round 1', max_length=150)),
                ('interview_type', models.CharField(choices=[('VIDEO', 'Video Conference (Google Meet / Zoom)'), ('IN_PERSON', 'On-Site In-Person'), ('PHONE', 'Telephonic Screen')], default='VIDEO', max_length=50)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('meeting_link', models.CharField(default='https://meet.google.com/ems-recruitment-room', max_length=255)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled')], default='SCHEDULED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interviewers', models.ManyToManyField(related_name='scheduled_interviews', to='employees.employee')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='recruitment.jobapplication')),
            ],
        ),
        migrations.CreateModel(
            name='JobRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Senior Cloud Architect, HR Talent Partner', max_length=200)),
                ('requisition_code', models.CharField(max_length=50, unique=True)),
                ('headcount', models.PositiveIntegerField(default=1)),
                ('min_experience_years', models.DecimalField(decimal_places=1, default=Decimal('3.0'), max_digits=4)),
                ('max_experience_years', models.DecimalField(decimal_places=1, default=Decimal('8.0'), max_digits=4)),
                ('budget_min', models.DecimalField(decimal_places=2, default=Decimal('800000.00'), max_digits=12)),
                ('budget_max', models.DecimalField(decimal_places=2, default=Decimal('1500000.00'), max_digits=12)),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full-Time Regular'), ('CONTRACT', 'Contractor'), ('INTERN', 'Internship')], default='FULL_TIME', max_length=50)),
                ('work_location', models.CharField(default='Bengaluru HQ / Hybrid', max_length=150)),
                ('priority', models.CharField(choices=[('LOW', 'Low Priority'), ('MEDIUM', 'Medium Priority'), ('HIGH', 'High Priority'), ('URGENT', 'Critical / Urgent')], default='HIGH', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted for Approval'), ('APPROVED', 'Approved by Leadership'), ('REJECTED', 'Rejected'), ('CLOSED', 'Fulfilled / Closed')], default='APPROVED', max_length=20)),
                ('justification', models.TextField(help_text='Business justification for hiring')),
                ('job_description', models.TextField()),
                ('required_skills', models.TextField(help_text='Comma-separated skills e.g. Python, Django, AWS, PostgreSQL')),
                ('target_hire_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_requisitions', to='organization.department')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.designation')),
                ('hiring_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_requisitions', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Job Requisition',
                'verbose_name_plural': 'Job Requisitions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_slug', models.SlugField(max_length=200, unique=True)),
                ('is_published', models.BooleanField(default=True)),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
                ('application_deadline', models.DateField()),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('applications_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requisition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='posting', to='recruitment.jobrequisition')),
            ],
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job_requisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment.jobrequisition'),
        ),
        migrations.CreateModel(
            name='OfferLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_code', models.CharField(max_length=50, unique=True)),
                ('offered_designation', models.CharField(max_length=150)),
                ('offered_ctc_annual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('joining_date', models.DateField()),
                ('probation_months', models.IntegerField(default=6)),
                ('offer_valid_until', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVAL_PENDING', 'Pending Internal Signoff'), ('SENT', 'Extended to Candidate'), ('ACCEPTED', 'Accepted & Signed'), ('DECLINED', 'Declined by Candidate'), ('EXPIRED', 'Offer Expired')], default='SENT', max_length=30)),
                ('signed_copy', models.FileField(blank=True, null=True, upload_to='offer_letters/')),
                ('candidate_acceptance_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer_letter', to='recruitment.jobapplication')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.department')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_rating', models.IntegerField(choices=[(1, '1-Poor'), (2, '2-Fair'), (3, '3-Good'), (4, '4-Very Good'), (5, '5-Exceptional')], default=4)),
                ('communication_rating', models.IntegerField(choices=[(1, '1-Poor'), (2, '2-Fair'), (3, '3-Good'), (4, '4-Very Good'), (5, '5-Exceptional')], default=4)),
                ('problem_solving_rating', models.IntegerField(choices=[(1, '1-Poor'), (2, '2-Fair'), (3, '3-Good'), (4, '4-Very Good'), (5, '5-Exceptional')], default=5)),
                ('cultural_fit_rating', models.IntegerField(choices=[(1, '1-Poor'), (2, '2-Fair'), (3, '3-Good'), (4, '4-Very Good'), (5, '5-Exceptional')], default=4)),
                ('recommendation', models.CharField(choices=[('STRONG_HIRE', 'Strong Hire'), ('HIRE', 'Hire'), ('NEUTRAL', 'Neutral / Borderline'), ('NO_HIRE', 'Do Not Hire')], default='HIRE', max_length=30)),
                ('key_strengths', models.TextField()),
                ('areas_for_improvement', models.TextField(blank=True)),
                ('summary_comments', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='recruitment.interviewschedule')),
            ],
            options={
                'unique_together': {('interview', 'interviewer')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('job_requisition', 'candidate')},
        ),
    ]
