# Generated by Django 6.1 on 2026-08-25 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequisition',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_requisitions', to='organization.department'),
        ),
        migrations.AlterField(
            model_name='jobrequisition',
            name='job_description',
            field=models.TextField(blank=True, default='Job overview and core responsibilities'),
        ),
        migrations.AlterField(
            model_name='jobrequisition',
            name='justification',
            field=models.TextField(blank=True, default='Headcount growth'),
        ),
        migrations.AlterField(
            model_name='offerletter',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.department'),
        ),
    ]
