# Generated by Django 6.1 on 2026-08-24 09:30

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Review Cycle',
                'verbose_name_plural': 'Review Cycles',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_skills_rating', models.DecimalField(decimal_places=1, default=3.0, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('1.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))])),
                ('communication_rating', models.DecimalField(decimal_places=1, default=3.0, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('1.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))])),
                ('productivity_rating', models.DecimalField(decimal_places=1, default=3.0, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('1.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))])),
                ('leadership_rating', models.DecimalField(decimal_places=1, default=3.0, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('1.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))])),
                ('final_score', models.DecimalField(decimal_places=2, default=3.0, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('1.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))])),
                ('strengths', models.TextField(blank=True, null=True)),
                ('areas_of_improvement', models.TextField(blank=True, null=True)),
                ('manager_comments', models.TextField(blank=True, null=True)),
                ('is_submitted', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_evaluations', to='employees.employee')),
                ('evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_evaluations', to='employees.employee')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='performance.reviewcycle')),
            ],
            options={
                'verbose_name': 'Performance Evaluation',
                'verbose_name_plural': 'Performance Evaluations',
                'ordering': ['-cycle__start_date'],
                'unique_together': {('employee', 'cycle')},
            },
        ),
    ]
