# Generated by Django 6.1 on 2026-08-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewcycle',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=20),
        ),
    ]
