# Generated by Django 6.1 on 2026-08-25 04:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Q3 Statutory Labor Audit 2026', max_length=200)),
                ('audit_date', models.DateField(default=django.utils.timezone.now)),
                ('auditor_agency', models.CharField(default='KPMG Internal Audit Advisory', max_length=150)),
                ('lead_auditor', models.CharField(default='Vikramaditya Sengupta', max_length=150)),
                ('score_percentage', models.IntegerField(default=98, help_text='Audit compliance score %')),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed & Certified'), ('ACTION_REQUIRED', 'Remediation Required')], default='COMPLETED', max_length=30)),
                ('findings_count', models.IntegerField(default=2)),
                ('summary_report', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='POSHCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=50, unique=True)),
                ('incident_date', models.DateField()),
                ('reported_date', models.DateField(default=django.utils.timezone.now)),
                ('is_confidential', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('REPORTED', 'Case Registered'), ('INQUIRY_ONGOING', 'Inquiry Committee Convened'), ('HEARING', 'Hearing & Evidence'), ('REPORT_SUBMITTED', 'Final Report Submitted'), ('CLOSED', 'Closed & Resolved')], default='CLOSED', max_length=30)),
                ('inquiry_findings', models.TextField(help_text='Protected confidential findings')),
                ('action_taken', models.TextField()),
                ('resolved_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatutoryRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('register_type', models.CharField(choices=[('FORM_A', 'Form A - Employee Register (Maternity / Wages)'), ('FORM_B', 'Form B - Wage Register & Overtime Records'), ('FORM_C', 'Form C - Loan and Advance Deductions'), ('FORM_D', 'Form D - Bonus & Gratuity Calculation Register'), ('FACTORY_ACT', 'Factories Act / Shops & Establishment Inspection Register')], max_length=50)),
                ('period_year', models.IntegerField(default=2026)),
                ('period_month', models.IntegerField(default=8)),
                ('verified_by_officer', models.CharField(default='Priya Patel, Lead Compliance Officer', max_length=150)),
                ('is_signed', models.BooleanField(default=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='compliance_registers/')),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='POSHCommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(choices=[('PRESIDING_OFFICER', 'Presiding Officer (Senior Woman Leader)'), ('INTERNAL_MEMBER', 'Internal Committee Member'), ('EXTERNAL_NGO_MEMBER', 'External Legal / NGO Specialist')], default='INTERNAL_MEMBER', max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posh_roles', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyAcknowledgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(help_text='e.g. Code of Business Conduct 2026, Information Security Policy', max_length=150)),
                ('version', models.CharField(default='v3.2', max_length=20)),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(default='127.0.0.1')),
                ('is_compliant', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_acknowledgments', to='employees.employee')),
            ],
            options={
                'unique_together': {('employee', 'policy_name', 'version')},
            },
        ),
    ]
