# Generated by Django 6.1 on 2026-08-24 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecognitionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('badge_icon', models.CharField(default='bi-star-fill', help_text='Bootstrap Icon class', max_length=50)),
                ('badge_color', models.CharField(default='#f59e0b', max_length=20)),
                ('points', models.PositiveIntegerField(default=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Recognition Category',
                'verbose_name_plural': 'Recognition Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeRecognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('points_awarded', models.PositiveIntegerField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognitions_received', to='employees.employee')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognitions_given', to='employees.employee')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognitions', to='recognition.recognitioncategory')),
            ],
            options={
                'verbose_name': 'Employee Recognition',
                'verbose_name_plural': 'Employee Recognitions',
                'ordering': ['-created_at'],
            },
        ),
    ]
