# Generated by Django 6.1 on 2026-08-25 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Auto-Welcome Email & Task Generation on Hire', max_length=200)),
                ('trigger_event', models.CharField(choices=[('EMPLOYEE_JOINED', 'When a new employee joins (Onboarding)'), ('LEAVE_APPROVED', 'When a leave request is approved'), ('PROBATION_DUE', 'When employee probation review date arrives'), ('WORK_ANNIVERSARY', 'On employee work anniversary milestone'), ('BIRTHDAY_ALERT', 'On employee birthday'), ('EXPENSE_SUBMITTED', 'When high-value expense claim is filed'), ('PAYROLL_PROCESSED', 'When monthly payroll run is completed')], max_length=50)),
                ('action_type', models.CharField(choices=[('DISPATCH_EMAIL', 'Dispatch Automated Notification Email'), ('SEND_IN_APP_ALERT', 'Send Instant In-App System Alert'), ('CREATE_TASK', 'Create Follow-up Task for Manager'), ('TRIGGER_WEBHOOK', 'Fire Webhook to External ERP / Slack'), ('AWARD_KUDOS_BADGE', 'Award Automated Recognition Badge')], max_length=50)),
                ('action_payload', models.TextField(help_text='JSON or configuration parameters for the action')),
                ('is_active', models.BooleanField(default=True)),
                ('total_executions', models.IntegerField(default=0)),
                ('last_executed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Executed Successfully'), ('FAILED', 'Execution Error'), ('SKIPPED', 'Conditions Not Met')], default='SUCCESS', max_length=20)),
                ('details', models.TextField()),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='automation.automationrule')),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
    ]
