# Generated by Django 6.1 on 2026-08-25 04:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('survey_type', models.CharField(choices=[('ENPS', 'eNPS Quarterly Workforce Survey'), ('PULSE', 'Monthly Morale Pulse Check'), ('ONBOARDING', '30-Day Onboarding Feedback'), ('EXIT', 'Confidential Exit Survey'), ('CUSTOM', 'Custom Organizational Survey')], default='ENPS', max_length=30)),
                ('description', models.TextField()),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField()),
                ('is_anonymous', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('target_responses_count', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('prompt_text', models.CharField(max_length=300)),
                ('question_type', models.CharField(choices=[('RATING_10', '1-10 Scale (eNPS)'), ('RATING_5', '1-5 Stars (Likert Scale)'), ('TEXT', 'Open-Ended Qualitative Text'), ('CHOICE', 'Multiple Choice Single Selection')], default='RATING_10', max_length=30)),
                ('choices_csv', models.CharField(blank=True, help_text='Comma separated options if Multiple Choice', max_length=255)),
                ('is_required', models.BooleanField(default=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.survey')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SurveySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('enps_score', models.IntegerField(blank=True, help_text='0-10 rating', null=True)),
                ('qualitative_feedback', models.TextField(blank=True)),
                ('sentiment_label', models.CharField(choices=[('POSITIVE', 'Promoter / High Satisfaction'), ('PASSIVE', 'Passive / Neutral'), ('DETRACTOR', 'Detractor / At-Risk')], default='POSITIVE', max_length=30)),
                ('employee', models.ForeignKey(blank=True, help_text='Null if 100% anonymous', null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='surveys.survey')),
            ],
        ),
    ]
