# Generated by Django 6.1 on 2026-08-25 04:56

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Aryabhata Boardroom, Ramanujan Brainstorm Pod', max_length=100)),
                ('building', models.CharField(default='Tower Alpha', max_length=100)),
                ('floor', models.CharField(default='Floor 3', max_length=50)),
                ('capacity_seats', models.IntegerField(default=12)),
                ('has_video_conferencing', models.BooleanField(default=True)),
                ('has_whiteboard', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TravelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(help_text='e.g. AWS Summit London 2026, Client On-site Workshop', max_length=200)),
                ('origin_city', models.CharField(default='Bengaluru', max_length=100)),
                ('destination_city', models.CharField(default='San Francisco / London', max_length=100)),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField()),
                ('flight_preference', models.CharField(default='Economy Non-stop', max_length=100)),
                ('hotel_needed', models.BooleanField(default=True)),
                ('advance_cash_requested', models.DecimalField(decimal_places=2, default=Decimal('50000.00'), max_digits=10)),
                ('estimated_total_cost', models.DecimalField(decimal_places=2, default=Decimal('180000.00'), max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Manager Approval'), ('APPROVED', 'Approved & Booked'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Travel Completed')], default='APPROVED', max_length=20)),
                ('manager_approval_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_requests', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='VisitorPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=150)),
                ('visitor_company', models.CharField(default='External Partner / Client', max_length=150)),
                ('visitor_email', models.EmailField(max_length=254)),
                ('visitor_phone', models.CharField(max_length=30)),
                ('visit_date', models.DateField(default=django.utils.timezone.now)),
                ('pass_code', models.CharField(max_length=50, unique=True)),
                ('purpose', models.CharField(default='Quarterly Strategic Planning', max_length=200)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('badge_number', models.CharField(default='VIS-042', max_length=30)),
                ('host_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_visitors', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='DeskBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(default='Tower Alpha', max_length=100)),
                ('floor', models.CharField(default='Floor 4 - Tech Hub', max_length=50)),
                ('desk_number', models.CharField(default='DESK-4A-12', max_length=30)),
                ('booking_date', models.DateField(default=django.utils.timezone.now)),
                ('time_slot', models.CharField(choices=[('FULL_DAY', 'Full Day (9 AM - 6 PM)'), ('MORNING', 'Morning (8 AM - 1 PM)'), ('EVENING', 'Afternoon/Evening (1 PM - 8 PM)')], default='FULL_DAY', max_length=30)),
                ('has_dual_monitors', models.BooleanField(default=True)),
                ('is_checked_in', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desk_bookings', to='employees.employee')),
            ],
            options={
                'unique_together': {('building', 'floor', 'desk_number', 'booking_date', 'time_slot')},
            },
        ),
    ]
