# Generated by Django 6.1 on 2026-08-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deskbooking',
            name='status',
            field=models.CharField(default='CONFIRMED', max_length=30),
        ),
    ]
