# Generated by Django 6.1 on 2026-08-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('action', models.CharField(choices=[('CREATE', 'Create Record'), ('READ', 'Read / Access'), ('UPDATE', 'Update Record'), ('DELETE', 'Delete Record'), ('APPROVE', 'Approve Request'), ('REJECT', 'Reject Request'), ('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('SECURITY', 'Security Event')], db_index=True, max_length=20)),
                ('module', models.CharField(db_index=True, max_length=50)),
                ('record_id', models.CharField(blank=True, max_length=50, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BackupConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_type', models.CharField(default='FULL_DATABASE_BACKUP', max_length=50)),
                ('frequency', models.CharField(default='DAILY_MIDNIGHT', max_length=30)),
                ('storage_location', models.CharField(default='local_backups/database/', max_length=255)),
                ('last_backup_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='CONFIGURED_AND_HEALTHY', max_length=30)),
                ('retention_days', models.PositiveIntegerField(default=30)),
            ],
            options={
                'verbose_name': 'Backup Configuration',
                'verbose_name_plural': 'Backup Configurations',
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Security Event',
                'verbose_name_plural': 'Security Events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('GENERAL', 'General Configuration'), ('SECURITY', 'Security & Sessions'), ('ATTENDANCE', 'Attendance Rules'), ('LEAVE', 'Leave Policies'), ('NOTIFICATIONS', 'Notification Preferences')], default='GENERAL', max_length=50)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'ordering': ['category', 'key'],
            },
        ),
    ]
