# Generated by Django 6.1 on 2026-08-24 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeWorkloadMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workload_score', models.PositiveIntegerField(default=0, help_text='Normalized workload score from 0 to 100')),
                ('active_tasks_count', models.PositiveIntegerField(default=0)),
                ('estimated_task_hours', models.DecimalField(decimal_places=1, default=0.0, max_digits=6)),
                ('project_allocation_count', models.PositiveIntegerField(default=0)),
                ('overdue_tasks_count', models.PositiveIntegerField(default=0)),
                ('utilization_status', models.CharField(choices=[('UNDERUTILIZED', 'Underutilized (<35%)'), ('BALANCED', 'Balanced (35-75%)'), ('OPTIMAL', 'Optimal (75-85%)'), ('OVERLOADED', 'Overloaded (>85%)')], default='BALANCED', max_length=20)),
                ('last_calculated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workload_metric', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Employee Workload Metric',
                'verbose_name_plural': 'Employee Workload Metrics',
                'ordering': ['-workload_score'],
            },
        ),
        migrations.CreateModel(
            name='WorkloadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workload_score', models.PositiveIntegerField()),
                ('active_tasks_count', models.PositiveIntegerField()),
                ('recorded_date', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workload_history', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Workload History',
                'verbose_name_plural': 'Workload Histories',
                'ordering': ['-recorded_date'],
            },
        ),
    ]
