# Generated by Django 6.1 on 2026-08-24 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('report_type', models.CharField(choices=[('EMPLOYEE', 'Employee Headcount Report'), ('ATTENDANCE', 'Workforce Attendance Report'), ('LEAVE', 'Leave Utilization Report'), ('PROJECT', 'Project Progress & Task Tracking'), ('PERFORMANCE', 'Performance Analytics & Ratings'), ('TRAINING', 'Skill & Training Compliance'), ('EXPENSE', 'Expense & Asset Tracking'), ('HELPDESK', 'Helpdesk SLA Performance')], max_length=50)),
                ('filters_applied', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Report',
                'verbose_name_plural': 'Saved Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
