# Generated by Django 6.1 on 2026-08-24 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(choices=[('ADMIN', 'Administrator'), ('HR', 'HR Manager'), ('MANAGER', 'Team Manager'), ('EMPLOYEE', 'Employee')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_system_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('AUTH', 'Authentication'), ('EMP', 'Employee Management'), ('ORG', 'Organization Management'), ('PERM', 'Roles & Permissions'), ('ATT', 'Attendance Management'), ('LEAVE', 'Leave Management'), ('SHIFT', 'Shift & Holiday Management'), ('WORKLOAD', 'Workload Management'), ('PROJ', 'Project Management'), ('TASK', 'Task Management'), ('SKILL', 'Skills Management'), ('GOAL', 'Goals Management'), ('PERF', 'Performance Management'), ('TRAIN', 'Training & Development'), ('RECOG', 'Recognition & Feedback'), ('ASSET', 'Asset Management'), ('EXP', 'Expense Management'), ('HELP', 'Helpdesk / Support'), ('DOC', 'Document Management'), ('ANNC', 'Announcements & Events'), ('NOTIF', 'Notifications'), ('INSIGHT', 'Smart Insights'), ('REP', 'Reports & Analytics'), ('AUDIT', 'Audit & System Administration')], max_length=30)),
                ('can_create', models.BooleanField(default=False)),
                ('can_read', models.BooleanField(default=True)),
                ('can_update', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_approve', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='permissions.role')),
            ],
            options={
                'verbose_name': 'Module Permission',
                'verbose_name_plural': 'Module Permissions',
                'unique_together': {('role', 'module')},
            },
        ),
    ]
