# Generated by Django 6.1 on 2026-08-25 04:56

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Star Health Corporate Floater 5L', max_length=200)),
                ('policy_number', models.CharField(max_length=100, unique=True)),
                ('provider_name', models.CharField(default='ICICI Lombard / Star Health', max_length=150)),
                ('policy_type', models.CharField(choices=[('GMC', 'Group Mediclaim Policy (Family Floater)'), ('GPA', 'Group Personal Accident'), ('GTL', 'Group Term Life Insurance')], default='GMC', max_length=30)),
                ('sum_insured', models.DecimalField(decimal_places=2, default=Decimal('500000.00'), max_digits=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('tpa_name', models.CharField(default='Medi Assist TPA Services', help_text='Third Party Administrator', max_length=150)),
                ('tpa_toll_free', models.CharField(default='1800-425-9449', max_length=50)),
                ('cashless_hospitals_count', models.IntegerField(default=12000)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeInsuranceEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=50, unique=True)),
                ('enrolled_date', models.DateField(default=django.utils.timezone.now)),
                ('sum_insured_allocated', models.DecimalField(decimal_places=2, default=Decimal('500000.00'), max_digits=12)),
                ('total_claims_utilized', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_enrollment', to='employees.employee')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='benefits.insurancepolicy')),
            ],
        ),
        migrations.CreateModel(
            name='FlexibleBenefitPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(default='2026-2027', max_length=20)),
                ('total_fbp_budget', models.DecimalField(decimal_places=2, default=Decimal('120000.00'), max_digits=12)),
                ('meal_card_allowance', models.DecimalField(decimal_places=2, default=Decimal('26400.00'), max_digits=10)),
                ('fuel_driver_allowance', models.DecimalField(decimal_places=2, default=Decimal('30000.00'), max_digits=10)),
                ('books_periodicals', models.DecimalField(decimal_places=2, default=Decimal('15000.00'), max_digits=10)),
                ('internet_telecom', models.DecimalField(decimal_places=2, default=Decimal('24000.00'), max_digits=10)),
                ('gym_wellness_reimbursement', models.DecimalField(decimal_places=2, default=Decimal('24600.00'), max_digits=10)),
                ('is_locked', models.BooleanField(default=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fbp_plan', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_id', models.CharField(max_length=50, unique=True)),
                ('patient_name', models.CharField(max_length=150)),
                ('hospital_name', models.CharField(max_length=200)),
                ('admission_date', models.DateField()),
                ('discharge_date', models.DateField()),
                ('claimed_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('approved_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('diagnosis', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted to TPA'), ('UNDER_REVIEW', 'Under Document Verification'), ('APPROVED', 'Approved for Cashless/Reimbursement'), ('SETTLED', 'Claim Amount Settled & Paid'), ('REJECTED', 'Claim Rejected by Insurer')], default='SUBMITTED', max_length=30)),
                ('settled_date', models.DateField(blank=True, null=True)),
                ('tpa_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='benefits.employeeinsuranceenrollment')),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceDependent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('relationship', models.CharField(choices=[('SPOUSE', 'Spouse / Partner'), ('CHILD_1', 'Child 1'), ('CHILD_2', 'Child 2'), ('PARENT_1', 'Father / Mother-in-Law'), ('PARENT_2', 'Mother / Father-in-Law')], max_length=30)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('health_card_number', models.CharField(blank=True, max_length=50)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='benefits.employeeinsuranceenrollment')),
            ],
        ),
    ]
