# Generated by Django 6.1 on 2026-08-25 04:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=50, unique=True)),
                ('issued_date', models.DateField(default=django.utils.timezone.now)),
                ('last_designation', models.CharField(max_length=150)),
                ('joining_date', models.DateField()),
                ('relieving_date', models.DateField()),
                ('conduct_remarks', models.CharField(default='Exemplary and Professional', max_length=100)),
                ('authorized_signatory_name', models.CharField(default='Aarav Sharma, Chief People Officer', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_certificates', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='OnboardingWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joining_date', models.DateField(default=django.utils.timezone.now)),
                ('probation_period_months', models.IntegerField(default=6)),
                ('probation_end_date', models.DateField()),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated / In Progress'), ('VERIFICATION', 'Document Verification'), ('COMPLETED', 'Onboarding Complete'), ('CANCELLED', 'Offer Rescinded')], default='INITIATED', max_length=30)),
                ('welcome_email_sent', models.BooleanField(default=False)),
                ('it_assets_assigned', models.BooleanField(default=False)),
                ('hr_orientation_completed', models.BooleanField(default=False)),
                ('id_badge_issued', models.BooleanField(default=False)),
                ('bank_details_verified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_workflow', to='employees.employee')),
                ('mentor_buddy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentored_onboardings', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='OnboardingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('IT_SETUP', 'IT & System Setup'), ('HR_DOCS', 'HR Documentation'), ('TRAINING', 'Initial Training & Compliance'), ('TEAM', 'Team Introductions & 1-on-1s')], default='HR_DOCS', max_length=50)),
                ('due_date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='lifecycle.onboardingworkflow')),
            ],
        ),
        migrations.CreateModel(
            name='ProbationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField(default=django.utils.timezone.now)),
                ('performance_score', models.IntegerField(choices=[(1, '1-Unsatisfactory'), (2, '2-Needs Improvement'), (3, '3-Meets Expectations'), (4, '4-Exceeds Expectations'), (5, '5-Outstanding')], default=4)),
                ('culture_fit_score', models.IntegerField(choices=[(1, '1-Poor'), (2, '2-Fair'), (3, '3-Good'), (4, '4-Very Good'), (5, '5-Exceptional')], default=4)),
                ('attendance_score', models.IntegerField(choices=[(1, '1-Poor'), (2, '2-Fair'), (3, '3-Good'), (4, '4-Very Good'), (5, '5-Exceptional')], default=5)),
                ('decision', models.CharField(choices=[('CONFIRM', 'Confirm Employment (Regularize)'), ('EXTEND', 'Extend Probation by 3 Months'), ('TERMINATE', 'Terminate / End Association')], default='CONFIRM', max_length=30)),
                ('manager_feedback', models.TextField()),
                ('is_approved_by_hr', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='probation_reviews', to='employees.employee')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conducted_probation_reviews', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ResignationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resignation_date', models.DateField(default=django.utils.timezone.now)),
                ('proposed_last_working_day', models.DateField()),
                ('approved_last_working_day', models.DateField(blank=True, null=True)),
                ('reason_category', models.CharField(choices=[('BETTER_OPPORTUNITY', 'Higher Studies / Better Opportunity'), ('CAREER_CHANGE', 'Career Change'), ('COMPENSATION', 'Compensation / Benefits'), ('PERSONAL', 'Personal / Family Relocation'), ('HEALTH', 'Health Reasons'), ('OTHER', 'Other')], default='BETTER_OPPORTUNITY', max_length=50)),
                ('detailed_reason', models.TextField()),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted by Employee'), ('MANAGER_REVIEW', 'Under Manager Review'), ('ACCEPTED', 'Accepted & Notice Period Active'), ('CLEARANCE', 'In Clearance & Handover Phase'), ('RELIEVED', 'Relieved / Completed Exit'), ('WITHDRAWN', 'Resignation Withdrawn'), ('REJECTED', 'Rejected / Retention Agreed')], default='SUBMITTED', max_length=30)),
                ('manager_comments', models.TextField(blank=True)),
                ('hr_exit_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resignation_request', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentClearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(choices=[('IT', 'IT Infrastructure & Hardware Return'), ('FINANCE', 'Finance, Loans & Travel Advances'), ('ADMIN', 'Admin, Access Cards & Lockers'), ('HR', 'HR, Medical Insurance & Documentation'), ('REPORTING_MANAGER', 'Reporting Manager Knowledge Handover')], max_length=50)),
                ('is_cleared', models.BooleanField(default=False)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('pending_items', models.TextField(blank=True, help_text='e.g. Laptop, Charger, YubiKey, ID Card')),
                ('remarks', models.TextField(blank=True)),
                ('cleared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('resignation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearances', to='lifecycle.resignationrequest')),
            ],
            options={
                'unique_together': {('resignation', 'department_name')},
            },
        ),
    ]
