# Generated by Django 6.1 on 2026-08-24 09:30

from django.db import migrations, models

import apps.employees.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(db_index=True, max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('personal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=25)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')], default='PREFER_NOT_TO_SAY', max_length=20)),
                ('marital_status', models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('OTHER', 'Other')], default='SINGLE', max_length=20)),
                ('blood_group', models.CharField(blank=True, max_length=10, null=True)),
                ('national_id', models.CharField(blank=True, max_length=50, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True)),
                ('current_address', models.TextField(blank=True, null=True)),
                ('permanent_address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(default='New York', max_length=100)),
                ('state', models.CharField(default='NY', max_length=100)),
                ('country', models.CharField(default='United States', max_length=100)),
                ('postal_code', models.CharField(default='10001', max_length=20)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=25, null=True)),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_joining', models.DateField()),
                ('employment_status', models.CharField(choices=[('ACTIVE', 'Active'), ('ON_LEAVE', 'On Leave'), ('PROBATION', 'Probation'), ('NOTICE_PERIOD', 'Notice Period'), ('RESIGNED', 'Resigned'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=20)),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full-Time Permanent'), ('PART_TIME', 'Part-Time'), ('CONTRACT', 'Contractor'), ('INTERN', 'Intern')], default='FULL_TIME', max_length=20)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to=apps.employees.models.employee_photo_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['employee_id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeBankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=50)),
                ('routing_or_ifsc_code', models.CharField(max_length=50)),
                ('branch_name', models.CharField(blank=True, max_length=150, null=True)),
                ('account_type', models.CharField(choices=[('SAVINGS', 'Savings'), ('CHECKING', 'Checking'), ('SALARY', 'Salary')], default='SAVINGS', max_length=20)),
            ],
            options={
                'verbose_name': 'Employee Bank Detail',
                'verbose_name_plural': 'Employee Bank Details',
            },
        ),
        migrations.CreateModel(
            name='EmployeeEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=150)),
                ('institution', models.CharField(max_length=200)),
                ('field_of_study', models.CharField(max_length=150)),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField(blank=True, null=True)),
                ('grade_or_gpa', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Employee Education',
                'verbose_name_plural': 'Employee Educations',
                'ordering': ['-end_year'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Employee Experience',
                'verbose_name_plural': 'Employee Experiences',
                'ordering': ['-start_date'],
            },
        ),
    ]
