# Generated by Django 6.1 on 2026-08-25 04:56

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRateCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(help_text='e.g. Lead Architect, Senior Fullstack Engineer', max_length=150)),
                ('hourly_billable_rate', models.DecimalField(decimal_places=2, default=Decimal('85.00'), max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('effective_start', models.DateField()),
                ('effective_end', models.DateField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_cards', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyTimesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField(help_text='Monday date of the week')),
                ('week_end_date', models.DateField(help_text='Sunday date of the week')),
                ('total_billable_hours', models.DecimalField(decimal_places=2, default=Decimal('40.00'), max_digits=6)),
                ('total_non_billable_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft / Editing'), ('SUBMITTED', 'Submitted to Manager'), ('APPROVED', 'Approved by Manager'), ('REJECTED', 'Rejected / Revisions Requested')], default='SUBMITTED', max_length=20)),
                ('approver_comments', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_timesheets', to='employees.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_timesheets', to='employees.employee')),
            ],
            options={
                'ordering': ['-week_start_date'],
                'unique_together': {('employee', 'week_start_date')},
            },
        ),
        migrations.CreateModel(
            name='TimesheetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('hours_logged', models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=4)),
                ('is_billable', models.BooleanField(default=True)),
                ('task_description', models.TextField(help_text='Detailed summary of deliverables worked on')),
                ('jira_or_ticket_id', models.CharField(blank=True, max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='timesheets.weeklytimesheet')),
            ],
        ),
    ]
