# Generated by Django 6.1 on 2026-08-25 15:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientratecard',
            name='effective_start',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
