# Generated by Django 6.1 on 2026-08-24 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ATTENDANCE', 'Attendance & Punctuality'), ('WORKLOAD', 'Workload & Capacity'), ('SKILL', 'Skills & Staffing'), ('GOAL', 'Goals & OKRs'), ('PERFORMANCE', 'Performance & Appraisals'), ('TRAINING', 'Training & Certifications'), ('MANAGER', 'Team Manager Intelligence')], db_index=True, max_length=30)),
                ('severity', models.CharField(choices=[('HIGH', 'High Priority / Critical'), ('MEDIUM', 'Medium Priority / Notice'), ('LOW', 'Low Priority / Info'), ('POSITIVE', 'Positive Achievement / Trend')], default='MEDIUM', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('what_detected', models.TextField()),
                ('why_detected', models.TextField(help_text='Mathematical / statistical explanation (e.g. standard deviations, rolling averages)')),
                ('supporting_data', models.JSONField(blank=True, default=dict)),
                ('recommendation', models.TextField()),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0.9, max_digits=4)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_insights', to='organization.department')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smart_insights', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Smart Insight',
                'verbose_name_plural': 'Smart Insights',
                'ordering': ['-created_at'],
            },
        ),
    ]
