# Generated by Django 6.1 on 2026-08-24 09:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('target_metric', models.CharField(default='Key Deliverables Completed', help_text='e.g. Revenue generated, bugs resolved, certification earned', max_length=100)),
                ('current_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('target_value', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('unit', models.CharField(default='Percentage (%)', max_length=30)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(db_index=True)),
                ('progress_percentage', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('ACHIEVED', 'Achieved'), ('MISSED', 'Missed'), ('CANCELLED', 'Cancelled')], default='IN_PROGRESS', max_length=20)),
                ('manager_feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_goals', to='employees.employee')),
                ('employee', models.ForeignKey(blank=True, help_text='Leave blank if this is a Team-level Goal', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='employees.employee')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_goals', to='organization.team')),
            ],
            options={
                'verbose_name': 'Goal',
                'verbose_name_plural': 'Goals',
                'ordering': ['due_date'],
            },
        ),
    ]
