# Generated by Django 6.1 on 2026-08-24 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('LEAVE', 'Leave'), ('TASK', 'Task'), ('PROJ', 'Project'), ('TRAIN', 'Training'), ('EXP', 'Expense'), ('ASSET', 'Asset'), ('DOC', 'Document'), ('HELP', 'Helpdesk'), ('ANNC', 'Announcement'), ('RECOG', 'Recognition'), ('SYSTEM', 'System Alert')], default='SYSTEM', max_length=20)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
